
local Test = import("typeTest")---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mercu.
--- DateTime: 2020/5/9 1:59
---
module("TestStructField")
TestStruct = struct {
    account = "string",
    password = "string",
    loginTime = "number",
}

TestStruct.account = 2