---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mercu.
--- DateTime: 2020/5/17 2:06
---

module("Interface")

NameProvider = interface{
    default = "string",
    common = "string",
}

func(NameProvider)()("string").GetDefaultName = function(self)
    return self.default
end

