---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mercu.
--- DateTime: 2020/6/6 22:45
---

export("Enum")
TestEnum = enum {
    "First", iota + 1,
    "Second",
    "Third",
}
print(TestEnum.First)