---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mercu.
--- DateTime: 2020/5/17 2:06
---

package("Interface")

NameProvider = interface {
    GetDefaultName = fn()(String),
    GetDefaultName2 = fn()(String, String),
}

--func(NameProvider)()("string").GetDefaultName = function(self)
--    return self.default
--end

